service: aws-inmet-nodejs

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  api-request:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
